version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - "/.env"
    ports:
      - "5432:5432"
    networks:
      - sharednetwork
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  sharednetwork:

volumes:
  db_data:
